### ISSUE TITLE
While running in a Linux azure function, FindCountry throw an exception

### ISSUE THREAD

**Issue by mortoize** [InquisitorJax/Wibci.CountryReverseGeocode#11]
Exception: System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
      4096 (0x1000) is an invalid culture identifier.
         at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
         at System.Globalization.RegionInfo..ctor(Int32 culture)
         at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.<>c.<FetchCurrencySymbol>b__2_0(CultureInfo x)
         at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
         at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FetchCurrencySymbol(String threeLetterISO)
         at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FindLocationInfo(GeoLocation location, AreaData data, List`1 coordinates)
         at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FindAreaData(GeoLocation location, List`1 jsonDataList)
         at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FindCountry(GeoLocation location)

https://stackoverflow.com/questions/41851613/culture-is-suddenly-not-supported-anymore-on-azure-web-app/41879861#41879861
https://andrewlock.net/dotnet-core-docker-and-cultures-solving-culture-issues-porting-a-net-core-app-from-windows-to-linux/

**Comment by jamsoft** [comment]
I've just encountered this in an AvaloniaUI application on a UK machine:

```
System.ArgumentException: Customized cultures cannot be passed by LCID, only by name. (Parameter 'culture')
   at System.Globalization.RegionInfo..ctor(Int32 culture)
   at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.<>c.<FetchCurrencySymbol>b__2_0(CultureInfo x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FetchCurrencySymbol(String threeLetterISO)
   at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FindLocationInfo(GeoLocation location, AreaData data, List`1 coordinates)
   at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FindAreaData(GeoLocation location, List`1 jsonDataList)
   at Wibci.CountryReverseGeocode.CountryReverseGeocodeService.FindCountry(GeoLocation location)
```

No idea how to fix this one.

**Comment by ghost** [comment]
I think in the latest master version this exception wouldn't happen anymore as the part of the code seems to be removed.
@InquisitorJax I know that you don't support this project anymore but can you push the latest version to nuget please?
